### ISSUE TITLE
Remove code climate github action

### ISSUE THREAD

**Issue by rodrigoaguilera** [beluga-php/docker-php#67]
In my latest PR https://github.com/beluga-php/docker-php/pull/66 I changed the action that was publishing the code coverage report because I thought the env variable CC_TEST_REPORTER_ID was somehow added to the CI builds of the master branch but I apparently is not.

Should we remove until someone is willing to configure code climate again?

**Comment by flavioheleno** [comment]
I *think* that CodeClimate was never really setup for this project/repository and was just here as part of forking the original project. I'll take a look at it right away :)

**Comment by flavioheleno** [comment]
CodeClimate is now setup: https://codeclimate.com/github/beluga-php/docker-php
I've re-run the action but there is still some issue when `prefer-lowest` combination is used. I don't have enough bandwidth right now to look at it, but I'll do later.

**Comment by rodrigoaguilera** [comment]
Here is an attempt to fix that https://github.com/beluga-php/docker-php/pull/68

**Comment by flavioheleno** [comment]
Great fix @rodrigoaguilera ! Thank you once more!
