### ISSUE TITLE
how to handle cpu, memory for a given container started

### ISSUE THREAD

**Issue by Sanix-Darker** [beluga-php/docker-php#85]
Hi, first, GG for maintaining this amazing dependency,
I was wondering if it's possible to set cpu / memory limitations like the docker CLI does here
i saw the original docker-php repo was doing that with 
```php
$hostConfig = new HostConfig();
$hostConfig->setCpusetCpus("0,2");
$hostConfig->setMemory(10);
```
 
is it also the case here ?
Thanks

**Comment by flavioheleno** [comment]
Hi @Sanix-Darker, by looking at the latest version of [HostConfig](https://github.com/beluga-php/docker-php-api/blob/main/src/Model/HostConfig.php) I'd guess you could use:
1. [setCpuShares](https://github.com/beluga-php/docker-php-api/blob/main/src/Model/HostConfig.php#L599)
2. [setMemory](https://github.com/beluga-php/docker-php-api/blob/main/src/Model/HostConfig.php#L618)
3. [setCpuPeriod](https://github.com/beluga-php/docker-php-api/blob/main/src/Model/HostConfig.php#L836)
4. [setCpuQuota](https://github.com/beluga-php/docker-php-api/blob/main/src/Model/HostConfig.php#L855)
5. [setCpusetCpus](https://github.com/beluga-php/docker-php-api/blob/main/src/Model/HostConfig.php#L916)

and many more to customize how your containers are executed within your hardware.

Also, note that this fork kept the same _ethos_ of the original library, meaning that most concepts you'd apply with `docker-php/docker-php`, you could probably apply to `beluga-php/docker-php` :)
